# Generated by Django 3.1.5 on 2021-03-14 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
