# Generated by Django 3.1.5 on 2021-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_title2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title2',
            new_name='location',
        ),
    ]
