# Generated by Django 3.1.5 on 2021-03-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
