# Generated by Django 3.1.5 on 2021-03-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210314_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name=['Jersey City, New Jersey']),
        ),
    ]
