# Generated by Django 3.1.5 on 2021-03-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210314_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='hello', max_length=100, verbose_name='Jersey City, New Jersey'),
        ),
    ]
