# Generated by Django 3.1.5 on 2021-03-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210314_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='West New York, New Jersey', max_length=100),
        ),
    ]
