# Generated by Django 3.1.5 on 2021-03-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210314_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Jersey City, New Jersey', max_length=100),
        ),
    ]
