# Generated by Django 3.1.5 on 2021-03-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210320_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='hello there', max_length=100),
        ),
    ]
