# Generated by Django 3.1.5 on 2021-03-29 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210328_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
