# Generated by Django 3.1.5 on 2021-04-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210330_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='detail_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
