# Generated by Django 3.1.5 on 2021-04-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profile_detail_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
