# Generated by Django 3.1.5 on 2021-04-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210408_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lat',
            new_name='detail_lat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lng',
            new_name='detail_lng',
        ),
    ]
