# Generated by Django 3.1.5 on 2021-03-05 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default='something'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default='something', max_length=100),
        ),
    ]
