# Generated by Django 3.1.5 on 2021-03-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20210304_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image2',
            field=models.ImageField(upload_to='post2_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.CharField(max_length=100),
        ),
    ]
