# Generated by Django 3.1.5 on 2021-03-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20210304_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(max_length=100),
        ),
    ]
