# Generated by Django 3.1.5 on 2021-03-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20210304_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(),
        ),
    ]
