# Generated by Django 3.1.5 on 2021-03-14 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20210314_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
