# Generated by Django 3.1.5 on 2021-03-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210314_2349'),
        ('front', '0009_post_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
