# Generated by Django 3.1.5 on 2021-03-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_post_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
    ]
